#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

readonly repo=shellbro/dropbox
readonly tag="$(cat VERSION)-$(date +%s)"

sudo docker pull "$repo:latest"
sudo docker tag "$repo:latest" "$repo:$tag"
sudo docker push "$repo:$tag"

git pull origin master
git tag "v$tag"
git push origin "v$tag"
